apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: payment-service-deployment
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: payment-service-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: payment-service-app
    spec:
      containers:
        - name: order-service-app
          image: chitrangad/payment-service:V4