spring.application.name=PAYMENT-SERVICE

server.port=9191

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# To auto create table
spring.jpa.hibernate.ddl-auto=create
# Enabling H2 Console
spring.h2.console.enabled=true
# Custom H2 Console URL
spring.h2.console.path=/h2-console
#Web allow
spring.h2.console.settings.web-allow-others=true
